#' Function to compute entropy
#'
#' @param p Numeric vector of values from th escaled periodogram generated by the fft function.
#'
#' @return Numeric with shanon entropy
#' @export
#'
shannon.entropy <- function(p)
{
  if (any(is.na(p)) || any(is.nan(p)))
    return(NA)
  if (min(p) < 0 || sum(p) <= 0)
    return(NA)
  p.norm <- p[p > 0]/sum(p)
  return(-sum(log2(p.norm)*p.norm))
}
